// Auto-generated by scripts/sync-three-realms.mjs — DO NOT EDIT
// Generated: 2026-05-13T06:46:01.670Z

export interface RealmFeatureCard {
  realmId?: RealmId
  title: string
  summary: string
  bullets: string[]
  sourcePath: string
  sourceUrl: string
  tags: string[]
}

export type RealmId = 'tianyu' | 'shenyu' | 'jingjie'

export const REALMS_FEATURES: Record<RealmId, RealmFeatureCard[]> = {
  tianyu: [
    {
      "title": "TITMS 快速開始指南",
      "summary": "```bash pip install -r requirements.txt ```",
      "bullets": [],
      "sourcePath": "天域/QUICKSTART.md",
      "sourceUrl": "https://github.com/iiooiioo888/Note/blob/main/%E5%A4%A9%E5%9F%9F/QUICKSTART.md",
      "tags": [
        "guide"
      ]
    },
    {
      "title": "三重智能任務管理系統 (TITMS)",
      "summary": "**Triple Intelligence Task Management System**",
      "bullets": [
        "四重LLM協同：主LLM（Solver）執行、次LLM（Verifier）驗證、助LLM（Archivist）記錄、總LLM（Coordinator）管理",
        "知識驅動決策：所有決策基於知識庫，而非孤立輸入",
        "動態上下文感知：任務自動關聯相關知識，提供完整決策背景",
        "閉環優化機制：驗證失敗自動觸發重新執行，持續優化方案"
      ],
      "sourcePath": "天域/README.md",
      "sourceUrl": "https://github.com/iiooiioo888/Note/blob/main/%E5%A4%A9%E5%9F%9F/README.md",
      "tags": [
        "overview"
      ]
    },
    {
      "title": "🗺️ TITMS 開發路線圖",
      "summary": "- [x] 四重LLM協同工作流 - [x] 知識庫管理（Markdown格式） - [x] 任務管理系統 - [x] 自動任務執行 - [x] TODO LIST 自動修正 - [x] Coordinator 任務管理協調 - [x] 迭代歷史追蹤 - [x] 結論文件生成 - [x] 錯誤處理增強",
      "bullets": [
        "[x] 四重LLM協同工作流",
        "[x] 知識庫管理（Markdown格式）",
        "[x] 任務管理系統",
        "[x] 自動任務執行"
      ],
      "sourcePath": "天域/ROADMAP.md",
      "sourceUrl": "https://github.com/iiooiioo888/Note/blob/main/%E5%A4%A9%E5%9F%9F/ROADMAP.md",
      "tags": [
        "roadmap"
      ]
    },
    {
      "title": "📋 任務執行指南",
      "summary": "系統已經為您生成了任務並保存到數據庫中。以下是執行這些任務的幾種方式：",
      "bullets": [
        "任務ID",
        "任務標題",
        "任務描述",
        "截止日期"
      ],
      "sourcePath": "天域/TASK_EXECUTION_GUIDE.md",
      "sourceUrl": "https://github.com/iiooiioo888/Note/blob/main/%E5%A4%A9%E5%9F%9F/TASK_EXECUTION_GUIDE.md",
      "tags": [
        "task"
      ]
    },
    {
      "title": "📋 任務數量控制指南",
      "summary": "當系統執行任務時，每次都會生成新的子任務，如果沒有適當的控制機制，任務數量會不斷增長，導致任務列表過於龐大，難以管理。",
      "bullets": [
        "更嚴格地檢查新任務與現有任務的相似度",
        "相似度超過0.75的任務會被自動跳過",
        "減少重複任務的創建",
        "Coordinator 現在更積極地合併相似任務"
      ],
      "sourcePath": "天域/TASK_MANAGEMENT_GUIDE.md",
      "sourceUrl": "https://github.com/iiooiioo888/Note/blob/main/%E5%A4%A9%E5%9F%9F/TASK_MANAGEMENT_GUIDE.md",
      "tags": [
        "task"
      ]
    }
  ],
  shenyu: [
    {
      "title": "🌟 神域平台 - 項目總覽",
      "summary": "神域平台是一個讓AI系統能夠互相監督、共享知識、協同工作的完整技術架構。通過標準化API接入機制，使各AI系統能夠註冊自身能力、共享知識庫、互相監督工作質量，從而形成一個自我進化的AI生態系統。",
      "bullets": [
        "Python 3.9+",
        "Docker & Docker Compose",
        "PostgreSQL 13+",
        "Redis 6+"
      ],
      "sourcePath": "神域/ch0-總覽 (Overview)/README.md",
      "sourceUrl": "https://github.com/iiooiioo888/Note/blob/main/%E7%A5%9E%E5%9F%9F/ch0-%E7%B8%BD%E8%A6%BD%20(Overview)/README.md",
      "tags": [
        "ch0",
        "module"
      ]
    },
    {
      "title": "神域平台終極技術規格說明書（模組級深度實現） - 第1章",
      "summary": "本章節由以下子章節組成，點擊鏈接可跳轉到相應內容：",
      "bullets": [
        "1.1 模組概述 - AI註冊中心的核心價值和定位",
        "1.2 詳細功能清單 - 包括核心功能和高級功能",
        "1.2.1 核心功能",
        "1.2.2 高級功能"
      ],
      "sourcePath": "神域/ch1-AI註冊中心 (AI Registry)/ch1-index.md",
      "sourceUrl": "https://github.com/iiooiioo888/Note/blob/main/%E7%A5%9E%E5%9F%9F/ch1-AI%E8%A8%BB%E5%86%8A%E4%B8%AD%E5%BF%83%20(AI%20Registry)/ch1-index.md",
      "tags": [
        "ch1",
        "module"
      ]
    },
    {
      "title": "神域平台終極技術規格說明書（模組級深度實現） - 第2章",
      "summary": "本章節由以下子章節組成，點擊鏈接可跳轉到相應內容：",
      "bullets": [
        "📋 系統詳細規格 - 完整系統規格文檔（包含系統架構、功能說明、硬件配置、部署方案等全面內容）",
        "2.1 模組概述 - 知識共享系統的核心價值和定位",
        "2.2 詳細功能清單 - 包括核心功能和高級功能",
        "2.3 技術架構 - 架構設計和服務交互"
      ],
      "sourcePath": "神域/ch2-知識共享系統 (Knowledge Sharing)/ch2-index.md",
      "sourceUrl": "https://github.com/iiooiioo888/Note/blob/main/%E7%A5%9E%E5%9F%9F/ch2-%E7%9F%A5%E8%AD%98%E5%85%B1%E4%BA%AB%E7%B3%BB%E7%B5%B1%20(Knowledge%20Sharing)/ch2-index.md",
      "tags": [
        "ch2",
        "module"
      ]
    },
    {
      "title": "神域平台終極技術規格說明書（模組級深度實現） - 第3章",
      "summary": "- [3.1 模組概述](ch3-1-模組概述.md) - [3.2 詳細功能清單](ch3-2-詳細功能清單.md) - [3.3 技術架構](ch3-3-技術架構.md) - [3.4 核心組件詳細實現](ch3-4-核心組件詳細實現.md) - [3.5 資料模型詳細定義](ch3-5-資料模型詳細定義.md) - [3.6 API詳細規範](ch3-6-API詳細規範.md) - [3.7 效能優化策略](ch3-7-效能優化策略.md) - [3.8 安全考慮](ch3-8-安全考慮.md) - [3.9 與其他模組的交互](ch3-9-與其他模組的交互.md)",
      "bullets": [
        "3.1 模組概述",
        "3.2 詳細功能清單",
        "3.3 技術架構",
        "3.4 核心組件詳細實現"
      ],
      "sourcePath": "神域/ch3-驗證與評估系統 (Verification and Evaluation)/ch3-index.md",
      "sourceUrl": "https://github.com/iiooiioo888/Note/blob/main/%E7%A5%9E%E5%9F%9F/ch3-%E9%A9%97%E8%AD%89%E8%88%87%E8%A9%95%E4%BC%B0%E7%B3%BB%E7%B5%B1%20(Verification%20and%20Evaluation)/ch3-index.md",
      "tags": [
        "ch3",
        "module"
      ]
    },
    {
      "title": "神域平台終極技術規格說明書（模組級深度實現） - 第4章",
      "summary": "- [4.1 模組概述](ch4-1-模組概述.md) - [4.2 詳細功能清單](ch4-2-詳細功能清單.md) - [4.3 技術架構](ch4-3-技術架構.md) - [4.4 核心組件詳細實現](ch4-4-核心組件詳細實現.md) - [4.5 資料模型詳細定義](ch4-5-資料模型詳細定義.md) - [4.6 API詳細規範](ch4-6-API詳細規範.md) - [4.7 效能優化策略](ch4-7-效能優化策略.md) - [4.8 安全考慮](ch4-8-安全考慮.md) - [4.9 與其他模組的交互](ch4-9-與其他模組的交互.md)",
      "bullets": [
        "4.1 模組概述",
        "4.2 詳細功能清單",
        "4.3 技術架構",
        "4.4 核心組件詳細實現"
      ],
      "sourcePath": "神域/ch4-信任管理系統 (Trust Management)/ch4-index.md",
      "sourceUrl": "https://github.com/iiooiioo888/Note/blob/main/%E7%A5%9E%E5%9F%9F/ch4-%E4%BF%A1%E4%BB%BB%E7%AE%A1%E7%90%86%E7%B3%BB%E7%B5%B1%20(Trust%20Management)/ch4-index.md",
      "tags": [
        "ch4",
        "module"
      ]
    },
    {
      "title": "神域平台終極技術規格說明書（模組級深度實現） - 第5章",
      "summary": "本章節由以下子章節組成，點擊鏈接可跳轉到相應內容：",
      "bullets": [
        "5.1 模組概述",
        "5.2 詳細功能清單",
        "5.3 技術架構",
        "5.4 核心組件詳細實現"
      ],
      "sourcePath": "神域/ch5-協作工作流引擎 (Collaboration Workflow)/ch5-index.md",
      "sourceUrl": "https://github.com/iiooiioo888/Note/blob/main/%E7%A5%9E%E5%9F%9F/ch5-%E5%8D%94%E4%BD%9C%E5%B7%A5%E4%BD%9C%E6%B5%81%E5%BC%95%E6%93%8E%20(Collaboration%20Workflow)/ch5-index.md",
      "tags": [
        "ch5",
        "module"
      ]
    },
    {
      "title": "神域平台終極技術規格說明書（模組級深度實現） - 第6章",
      "summary": "- [6.1 模組概述](ch6-1-模組概述.md) - [6.2 詳細功能清單](ch6-2-詳細功能清單.md) - [6.3 技術架構](ch6-3-技術架構.md) - [6.4 核心組件詳細實現](ch6-4-核心組件詳細實現.md) - [6.5 資料模型詳細定義](ch6-5-資料模型詳細定義.md) - [6.6 API詳細規範](ch6-6-API詳細規範.md) - [6.7 效能優化策略](ch6-7-效能優化策略.md) - [6.8 安全考慮](ch6-8-安全考慮.md) - [6.9 與其他模組的交互](ch6-9-與其他模組的交互.md)",
      "bullets": [
        "6.1 模組概述",
        "6.2 詳細功能清單",
        "6.3 技術架構",
        "6.4 核心組件詳細實現"
      ],
      "sourcePath": "神域/ch6-AI自理發展支持 (AI Development Support)/ch6-index.md",
      "sourceUrl": "https://github.com/iiooiioo888/Note/blob/main/%E7%A5%9E%E5%9F%9F/ch6-AI%E8%87%AA%E7%90%86%E7%99%BC%E5%B1%95%E6%94%AF%E6%8C%81%20(AI%20Development%20Support)/ch6-index.md",
      "tags": [
        "ch6",
        "module"
      ]
    },
    {
      "title": "神域平台終極技術規格說明書（模組級深度實現） - 第7章",
      "summary": "- [7.1 模組概述](ch7-1-模組概述.md) - [7.2 詳細功能清單](ch7-2-詳細功能清單.md) - [7.3 技術架構](ch7-3-技術架構.md) - [7.4 核心組件詳細實現](ch7-4-核心組件詳細實現.md) - [7.5 資料模型詳細定義](ch7-5-資料模型詳細定義.md) - [7.6 API詳細規範](ch7-6-API詳細規範.md) - [7.7 效能優化策略](ch7-7-效能優化策略.md) - [7.8 安全考慮](ch7-8-安全考慮.md) - [7.9 與其他模組的交互](ch7-9-與其他模組的交互.md)",
      "bullets": [
        "7.1 模組概述",
        "7.2 詳細功能清單",
        "7.3 技術架構",
        "7.4 核心組件詳細實現"
      ],
      "sourcePath": "神域/ch7-治理與合規中心 (Governance and Compliance)/ch7-index.md",
      "sourceUrl": "https://github.com/iiooiioo888/Note/blob/main/%E7%A5%9E%E5%9F%9F/ch7-%E6%B2%BB%E7%90%86%E8%88%87%E5%90%88%E8%A6%8F%E4%B8%AD%E5%BF%83%20(Governance%20and%20Compliance)/ch7-index.md",
      "tags": [
        "ch7",
        "module"
      ]
    },
    {
      "title": "🤖 神域平台 AI 開發指南",
      "summary": "- [快速開始](#快速開始) - [系統提示詞](#系統提示詞) - [開發場景](#開發場景) - [代碼模板](#代碼模板) - [AI協作模式](#ai協作模式) - [測試指南](#測試指南)",
      "bullets": [
        "快速開始",
        "系統提示詞",
        "開發場景",
        "代碼模板"
      ],
      "sourcePath": "神域/AI-DEVELOPMENT-GUIDE.md",
      "sourceUrl": "https://github.com/iiooiioo888/Note/blob/main/%E7%A5%9E%E5%9F%9F/AI-DEVELOPMENT-GUIDE.md",
      "tags": [
        "doc"
      ]
    },
    {
      "title": "🌟 神域平台知識庫 (Divine Domain Knowledge Base)",
      "summary": "- [系統概覽](#系統概覽) - [核心概念](#核心概念) - [技術架構](#技術架構) - [API路由體系](#api路由體系) - [AI協作機制](#ai協作機制) - [信任與評估](#信任與評估) - [常見模式](#常見模式) - [設計哲學](#設計哲學) - [最佳實踐](#最佳實踐)",
      "bullets": [
        "系統概覽",
        "核心概念",
        "技術架構",
        "API路由體系"
      ],
      "sourcePath": "神域/KNOWLEDGE-BASE.md",
      "sourceUrl": "https://github.com/iiooiioo888/Note/blob/main/%E7%A5%9E%E5%9F%9F/KNOWLEDGE-BASE.md",
      "tags": [
        "doc"
      ]
    },
    {
      "title": "📁 神域平台 - 項目結構（MD文檔版）",
      "summary": "✅ **優勢**: 1. **易讀性** - 代碼和文檔融為一體 2. **可搜索** - 所有內容都可以全文搜索 3. **版本控制友好** - Git diff更清晰 4. **學習友好** - 適合技術規格文檔 5. **在線瀏覽** - GitHub/GitLab直接渲染",
      "bullets": [
        "鏈接1",
        "鏈接2",
        "[x] 創建統一導航(README.md)",
        "[x] 完善AI註冊中心文檔"
      ],
      "sourcePath": "神域/PROJECT_STRUCTURE.md",
      "sourceUrl": "https://github.com/iiooiioo888/Note/blob/main/%E7%A5%9E%E5%9F%9F/PROJECT_STRUCTURE.md",
      "tags": [
        "doc"
      ]
    },
    {
      "title": "神域平台 - 架構優化完成報告",
      "summary": "基於對鏡界平台IT結構分析報告的深入研究，神域平台成功實施了全面的架構簡化與優化。通過遵循KISS原則和YAGNI原則，我們在保持核心功能完整的前提下，顯著降低了系統複雜度、部署難度和資源需求。",
      "bullets": [
        "[x] 移除Neo4j圖數據庫 → 使用PostgreSQL Recursive CTE",
        "[x] 移除Elasticsearch → 使用PostgreSQL全文搜索",
        "[x] 統一消息隊列 → 僅使用NATS（移除RabbitMQ）",
        "[x] 移除Go語言 → 統一使用Python"
      ],
      "sourcePath": "神域/架構優化完成報告.md",
      "sourceUrl": "https://github.com/iiooiioo888/Note/blob/main/%E7%A5%9E%E5%9F%9F/%E6%9E%B6%E6%A7%8B%E5%84%AA%E5%8C%96%E5%AE%8C%E6%88%90%E5%A0%B1%E5%91%8A.md",
      "tags": [
        "doc"
      ]
    },
    {
      "title": "神域平台 - 架構優化方案",
      "summary": "基於對鏡界平台的IT結構分析報告，我們發現了以下關鍵問題： - **技術棧過於複雜**：使用了過多的中間件和技術組件 - **部署架構過重**：最小部署需要太多組件 - **服務間依賴過於緊密**：所有模組都直接依賴相同的中間件 - **監控和日誌系統重複**：多個監控組件功能重疊",
      "bullets": [
        "技術棧過於複雜：使用了過多的中間件和技術組件",
        "部署架構過重：最小部署需要太多組件",
        "服務間依賴過於緊密：所有模組都直接依賴相同的中間件",
        "監控和日誌系統重複：多個監控組件功能重疊"
      ],
      "sourcePath": "神域/架構優化方案.md",
      "sourceUrl": "https://github.com/iiooiioo888/Note/blob/main/%E7%A5%9E%E5%9F%9F/%E6%9E%B6%E6%A7%8B%E5%84%AA%E5%8C%96%E6%96%B9%E6%A1%88.md",
      "tags": [
        "doc"
      ]
    },
    {
      "title": "🌟 神域平台 - 功能模塊拆解",
      "summary": "1. **高內聚低耦合** - 每個模塊有明確職責，依賴最小化 2. **獨立部署能力** - 模塊可單獨開發、測試和部署 3. **標準化接口** - 通過清晰API協議進行模塊交互 4. **可插拔架構** - 便於替換或升級特定功能 5. **獨立演進** - 各模塊可按不同節奏迭代發展",
      "bullets": [
        "管理AI實例的註冊、發現和生命週期",
        "提供AI能力描述與搜索功能",
        "維護AI基本狀態與可用性",
        "AI註冊與反註冊"
      ],
      "sourcePath": "神域/模塊功能.md",
      "sourceUrl": "https://github.com/iiooiioo888/Note/blob/main/%E7%A5%9E%E5%9F%9F/%E6%A8%A1%E5%A1%8A%E5%8A%9F%E8%83%BD.md",
      "tags": [
        "doc"
      ]
    },
    {
      "title": "🎉 神域平台 - 路由重組完成報告",
      "summary": "| 序號 | 舊名稱（複雜） | 新名稱（簡潔） | 長度減少 | |-----|--------------|--------------|----------| | 0 | `00-項目總覽` | `ch0-overview` | -4字符 | | 1 | `01-AI註冊中心 (AI Registry)` | `ch1-ai-registry` | -13字符 | | 2 | `02-知識共享系統 (Knowledge Sharing)` | `ch2-knowledge-sharing` | -8字符 | | 3 | `03-驗證與評估系統 (Verification and Evaluation)` | `ch3-veri",
      "bullets": [
        "文件夾總數: 8個",
        "平均名稱長度:",
        "舊: 24.5字符",
        "新: 13字符"
      ],
      "sourcePath": "神域/路由重組完成報告.md",
      "sourceUrl": "https://github.com/iiooiioo888/Note/blob/main/%E7%A5%9E%E5%9F%9F/%E8%B7%AF%E7%94%B1%E9%87%8D%E7%B5%84%E5%AE%8C%E6%88%90%E5%A0%B1%E5%91%8A.md",
      "tags": [
        "doc"
      ]
    }
  ],
  jingjie: [
    {
      "title": "第6章：AI輔助開发系統 (AI-Assisted Development System)",
      "summary": "**[← 返回第6章首頁](ch6-index.md)**",
      "bullets": [
        "自然語言交互，無需深入編程知識",
        "自動生成可運行的代碼",
        "提供詳細的註釋和說明",
        "快速生成爬蟲代碼，節省開發時間"
      ],
      "sourcePath": "鏡界/AI輔助開發 (AI-Assisted Development)/ch6-1-模組概述.md",
      "sourceUrl": "https://github.com/iiooiioo888/Note/blob/main/%E9%8F%A1%E7%95%8C/AI%E8%BC%94%E5%8A%A9%E9%96%8B%E7%99%BC%20(AI-Assisted%20Development)/ch6-1-%E6%A8%A1%E7%B5%84%E6%A6%82%E8%BF%B0.md",
      "tags": [
        "module"
      ]
    },
    {
      "title": "文檔維護腳本使用說明（Windows PowerShell）",
      "summary": "本資料夾包含兩個實用腳本，協助你在保留 Unicode/繁中檔名的前提下，安全地預覽與套用文檔結構優化：",
      "bullets": [
        "`preview-doc-ops.ps1`：預覽變更（不修改檔案）",
        "`apply-doc-ops.ps1`：套用變更（支援 `-WhatIf` 先行試跑）",
        "檔名簡繁統一（示例）：",
        "`ch1/ch1-10-最佳实践指南.md` → `ch1/ch1-10-最佳實踐指南.md`"
      ],
      "sourcePath": "鏡界/ops/README.md",
      "sourceUrl": "https://github.com/iiooiioo888/Note/blob/main/%E9%8F%A1%E7%95%8C/ops/README.md",
      "tags": [
        "module"
      ]
    },
    {
      "title": "第8章：分布式爬蟲集群管理系統 (Distributed Crawler Cluster Management System)",
      "summary": "**[← 返回第8章首頁](ch8-index.md)**",
      "bullets": [
        "高可用性：通過分布式架構和自動故障轉移，確保系統持續可用",
        "多節點部署：支持多個主節點和備用節點，實現高可用架構",
        "自動故障轉移：當主節點故障時，自動切換到備用節點，無縫接管服務",
        "健康檢查機制：定期檢查節點健康狀態，及時發現和處理故障"
      ],
      "sourcePath": "鏡界/分布式爬蟲集群 (Distributed Crawler Cluster)/ch8-1-模組概述.md",
      "sourceUrl": "https://github.com/iiooiioo888/Note/blob/main/%E9%8F%A1%E7%95%8C/%E5%88%86%E5%B8%83%E5%BC%8F%E7%88%AC%E8%9F%B2%E9%9B%86%E7%BE%A4%20(Distributed%20Crawler%20Cluster)/ch8-1-%E6%A8%A1%E7%B5%84%E6%A6%82%E8%BF%B0.md",
      "tags": [
        "module"
      ]
    },
    {
      "title": "媒體處理管道 (Media Processing Pipeline)",
      "summary": "**[← 返回第5章首頁](ch5-index.md)**",
      "bullets": [
        "← 返回第5章首頁",
        "5.2 詳細功能清單"
      ],
      "sourcePath": "鏡界/媒體處理管道 (Media Processing Pipeline)/ch5-1-模組概述.md",
      "sourceUrl": "https://github.com/iiooiioo888/Note/blob/main/%E9%8F%A1%E7%95%8C/%E5%AA%92%E9%AB%94%E8%99%95%E7%90%86%E7%AE%A1%E9%81%93%20(Media%20Processing%20Pipeline)/ch5-1-%E6%A8%A1%E7%B5%84%E6%A6%82%E8%BF%B0.md",
      "tags": [
        "module"
      ]
    },
    {
      "title": "第10章：實時數據處理引擎 (Real-time Data Processing Engine)",
      "summary": "**[← 返回第10章首頁](ch10-index.md)**",
      "bullets": [
        "批處理延遲高（分鐘到小時級別）",
        "無法及時響應異常事件",
        "實時監控能力不足",
        "缺少流式數據分析"
      ],
      "sourcePath": "鏡界/實時數據處理 (Real-time Data Processing)/ch10-1-模組概述.md",
      "sourceUrl": "https://github.com/iiooiioo888/Note/blob/main/%E9%8F%A1%E7%95%8C/%E5%AF%A6%E6%99%82%E6%95%B8%E6%93%9A%E8%99%95%E7%90%86%20(Real-time%20Data%20Processing)/ch10-1-%E6%A8%A1%E7%B5%84%E6%A6%82%E8%BF%B0.md",
      "tags": [
        "module"
      ]
    },
    {
      "title": "接入與集成層 (Access and Integration Layer)",
      "summary": "**[← 返回第9章首頁](ch9-index.md)**",
      "bullets": [
        "多模組協調與通信",
        "API閘道管理",
        "統一認證與授權",
        "事件驅動架構"
      ],
      "sourcePath": "鏡界/接入與集成層 (Access and Integration Layer)/ch9-1-模組概述.md",
      "sourceUrl": "https://github.com/iiooiioo888/Note/blob/main/%E9%8F%A1%E7%95%8C/%E6%8E%A5%E5%85%A5%E8%88%87%E9%9B%86%E6%88%90%E5%B1%A4%20(Access%20and%20Integration%20Layer)/ch9-1-%E6%A8%A1%E7%B5%84%E6%A6%82%E8%BF%B0.md",
      "tags": [
        "module"
      ]
    },
    {
      "title": "第7章：資料合規與安全中心 (Data Compliance and Security Center)",
      "summary": "**[← 返回第7章首頁](ch7-index.md)**",
      "bullets": [
        "7.2 詳細功能清單",
        "7.3 技術架構",
        "7.4 核心組件詳細實現",
        "← 返回第7章首頁"
      ],
      "sourcePath": "鏡界/數據合規與安全 (Data Compliance and Security)/ch7-1-模組概述.md",
      "sourceUrl": "https://github.com/iiooiioo888/Note/blob/main/%E9%8F%A1%E7%95%8C/%E6%95%B8%E6%93%9A%E5%90%88%E8%A6%8F%E8%88%87%E5%AE%89%E5%85%A8%20(Data%20Compliance%20and%20Security)/ch7-1-%E6%A8%A1%E7%B5%84%E6%A6%82%E8%BF%B0.md",
      "tags": [
        "module"
      ]
    },
    {
      "title": "數據處理工作流 (Data Processing Workflow)",
      "summary": "**[← 返回第4章首頁](ch4-index.md)**",
      "bullets": [
        "支援複雜的任務依賴關係",
        "動態工作流定義和執行",
        "條件分支和循環控制",
        "並行任務執行優化"
      ],
      "sourcePath": "鏡界/數據處理工作流 (Data Processing Workflow)/ch4-1-模組概述.md",
      "sourceUrl": "https://github.com/iiooiioo888/Note/blob/main/%E9%8F%A1%E7%95%8C/%E6%95%B8%E6%93%9A%E8%99%95%E7%90%86%E5%B7%A5%E4%BD%9C%E6%B5%81%20(Data%20Processing%20Workflow)/ch4-1-%E6%A8%A1%E7%B5%84%E6%A6%82%E8%BF%B0.md",
      "tags": [
        "module"
      ]
    },
    {
      "title": "第12章：數據質量管理中心 (Data Quality Management Center)",
      "summary": "**[← 返回第12章首頁](ch12-index.md)**",
      "bullets": [
        "減少人工清洗成本：80%",
        "減少數據錯誤損失：90%",
        "提高數據利用率：40%",
        "縮短數據準備時間：75%"
      ],
      "sourcePath": "鏡界/數據質量管理 (Data Quality Management)/ch12-1-模組概述.md",
      "sourceUrl": "https://github.com/iiooiioo888/Note/blob/main/%E9%8F%A1%E7%95%8C/%E6%95%B8%E6%93%9A%E8%B3%AA%E9%87%8F%E7%AE%A1%E7%90%86%20(Data%20Quality%20Management)/ch12-1-%E6%A8%A1%E7%B5%84%E6%A6%82%E8%BF%B0.md",
      "tags": [
        "module"
      ]
    },
    {
      "title": "第11章：智能調度與資源管理系統 (Intelligent Scheduling & Resource Management)",
      "summary": "**[← 返回第11章首頁](ch11-index.md)**",
      "bullets": [],
      "sourcePath": "鏡界/智能調度與資源管理 (Intelligent Scheduling & Resource Management)/ch11-1-模組概述.md",
      "sourceUrl": "https://github.com/iiooiioo888/Note/blob/main/%E9%8F%A1%E7%95%8C/%E6%99%BA%E8%83%BD%E8%AA%BF%E5%BA%A6%E8%88%87%E8%B3%87%E6%BA%90%E7%AE%A1%E7%90%86%20(Intelligent%20Scheduling%20%26%20Resource%20Management)/ch11-1-%E6%A8%A1%E7%B5%84%E6%A6%82%E8%BF%B0.md",
      "tags": [
        "module"
      ]
    },
    {
      "title": "網站指紋分析 (Website Fingerprinting)",
      "summary": "**[← 返回第2章首頁](ch2-index.md)**",
      "bullets": [
        "自動識別網站使用的技術棧（服務器、語言、框架、CMS等）",
        "為爬蟲策略選擇提供依據",
        "幫助開發者快速了解目標網站架構",
        "全面檢測網站的反爬策略"
      ],
      "sourcePath": "鏡界/網站指紋分析 (Website Fingerprinting)/ch2-1-模組概述.md",
      "sourceUrl": "https://github.com/iiooiioo888/Note/blob/main/%E9%8F%A1%E7%95%8C/%E7%B6%B2%E7%AB%99%E6%8C%87%E7%B4%8B%E5%88%86%E6%9E%90%20(Website%20Fingerprinting)/ch2-1-%E6%A8%A1%E7%B5%84%E6%A6%82%E8%BF%B0.md",
      "tags": [
        "module"
      ]
    },
    {
      "title": "第1章：資料源註冊中心 (Data Source Registry)",
      "summary": "**[← 返回第1章首頁](ch1-index.md)**",
      "bullets": [
        "採集和儲存每一個資料源的詳細元資訊，包括但不限於類型、結構描述（如Schema)、連接資訊、更新時間、擁有者、資料源狀態等。",
        "支援為資料源配置多層次標籤、分組與分類，實現高效組織與發現。",
        "提供基於多條件/全文索引的資料源快速檢索服務，底層採用高效能檢索引擎（如Elasticsearch），實現秒級響應。",
        "對接各類上下游業務模組，根據權限精準推薦及推送資料源。"
      ],
      "sourcePath": "鏡界/資料源註冊中心 (Data Source Registry)/ch1-1-模組概述.md",
      "sourceUrl": "https://github.com/iiooiioo888/Note/blob/main/%E9%8F%A1%E7%95%8C/%E8%B3%87%E6%96%99%E6%BA%90%E8%A8%BB%E5%86%8A%E4%B8%AD%E5%BF%83%20(Data%20Source%20Registry)/ch1-1-%E6%A8%A1%E7%B5%84%E6%A6%82%E8%BF%B0.md",
      "tags": [
        "module"
      ]
    },
    {
      "title": "資源健康監測 (Resource Health Monitoring)",
      "summary": "**[← 返回第3章首頁](ch3-index.md)**",
      "bullets": [
        "← 返回第3章首頁",
        "3.2 詳細功能清單"
      ],
      "sourcePath": "鏡界/資源健康監測 (Resource Health Monitoring)/ch3-1-模組概述.md",
      "sourceUrl": "https://github.com/iiooiioo888/Note/blob/main/%E9%8F%A1%E7%95%8C/%E8%B3%87%E6%BA%90%E5%81%A5%E5%BA%B7%E7%9B%A3%E6%B8%AC%20(Resource%20Health%20Monitoring)/ch3-1-%E6%A8%A1%E7%B5%84%E6%A6%82%E8%BF%B0.md",
      "tags": [
        "module"
      ]
    },
    {
      "title": "🤖 鏡界平台 AI 開發指南",
      "summary": "- [快速開始](#快速開始) - [系統提示詞](#系統提示詞) - [開發場景](#開發場景) - [代碼模板](#代碼模板) - [問題診斷](#問題診斷) - [測試指南](#測試指南)",
      "bullets": [
        "快速開始",
        "系統提示詞",
        "開發場景",
        "代碼模板"
      ],
      "sourcePath": "鏡界/AI-DEVELOPMENT-GUIDE.md",
      "sourceUrl": "https://github.com/iiooiioo888/Note/blob/main/%E9%8F%A1%E7%95%8C/AI-DEVELOPMENT-GUIDE.md",
      "tags": [
        "doc"
      ]
    },
    {
      "title": "🌐 鏡界平台知識庫 (Mirror World Knowledge Base)",
      "summary": "- [系統概覽](#系統概覽) - [核心概念](#核心概念) - [技術架構](#技術架構) - [API路由體系](#api路由體系) - [數據流程](#數據流程) - [常見模式](#常見模式) - [故障排查](#故障排查) - [最佳實踐](#最佳實踐)",
      "bullets": [
        "系統概覽",
        "核心概念",
        "技術架構",
        "API路由體系"
      ],
      "sourcePath": "鏡界/KNOWLEDGE-BASE.md",
      "sourceUrl": "https://github.com/iiooiioo888/Note/blob/main/%E9%8F%A1%E7%95%8C/KNOWLEDGE-BASE.md",
      "tags": [
        "doc"
      ]
    },
    {
      "title": "镜界平台终极技術规格說明书（模組级深度實現）",
      "summary": "- [1.1 模組概述](#11-模組概述) - [1.2 詳細功能清單](#12-詳細功能清單) - [1.2.1 核心功能](#121-核心功能) - [1.2.2 高级功能](#122-高级功能) - [1.3 技術架構](#13-技術架構) - [1.3.1 架構图](#131-架構图) - [1.3.2 服務边界與交互](#132-服務边界與交互) - [1.4 核心組件詳細實現](#14-核心組件詳細實現) - [1.4.1 元資料管理服務](#141-元資料管理服務) - [1.4.2 搜尋服務](#142-搜尋服務) - [1.4.3 分類管理服務](#143-分類管理服務)",
      "bullets": [
        "1.1 模組概述",
        "1.2 詳細功能清單",
        "1.2.1 核心功能",
        "1.2.2 高级功能"
      ],
      "sourcePath": "鏡界/qwer_v4 copy.md",
      "sourceUrl": "https://github.com/iiooiioo888/Note/blob/main/%E9%8F%A1%E7%95%8C/qwer_v4%20copy.md",
      "tags": [
        "doc"
      ]
    },
    {
      "title": "🔧 鏡界平台 - 中間件與技術棧一覽表",
      "summary": "| 中間件 | 用途 | 使用模組 | |--------|------|----------| | **PostgreSQL** | 元資料、關係型資料 | 資料源註冊中心, 數據處理工作流, 數據合規與安全, 接入與集成層, 智能調度與資源管理, 數據質量管理 | | **MongoDB** | 爬蟲資料、文檔儲存 | 網站指紋分析, 分布式爬蟲集群 | | **Redis** | 快取、隊列、分布式鎖 | 全部12個模組 | | **Elasticsearch** | 全文搜尋、日誌 | 資料源註冊中心, 分布式爬蟲集群, 接入與集成層 | | **ClickHouse** | 實時OLAP分析 | 實時數據處理 |",
      "bullets": [
        "Redis",
        "PostgreSQL",
        "Nginx",
        "Docker"
      ],
      "sourcePath": "鏡界/中間件與技術棧一覽表.md",
      "sourceUrl": "https://github.com/iiooiioo888/Note/blob/main/%E9%8F%A1%E7%95%8C/%E4%B8%AD%E9%96%93%E4%BB%B6%E8%88%87%E6%8A%80%E8%A1%93%E6%A3%A7%E4%B8%80%E8%A6%BD%E8%A1%A8.md",
      "tags": [
        "doc"
      ]
    },
    {
      "title": "📋 鏡界平台文檔重大修正說明",
      "summary": "**修正日期**：2025-11-03 **修正版本**：v2.1.0 **修正原因**：用戶反饋文檔存在誤導性描述與完成度矛盾問題",
      "bullets": [
        "聲稱\"核心完成度：100%\"",
        "但統計表顯示多項內容僅完成 20%-53%",
        "給讀者造成誤導",
        "未明確說明這是設計文檔還是實際產品"
      ],
      "sourcePath": "鏡界/修正說明_2025-11-03.md",
      "sourceUrl": "https://github.com/iiooiioo888/Note/blob/main/%E9%8F%A1%E7%95%8C/%E4%BF%AE%E6%AD%A3%E8%AA%AA%E6%98%8E_2025-11-03.md",
      "tags": [
        "doc"
      ]
    },
    {
      "title": "🌟 鏡界平台 - 持續擴展完成報告（第二輪）",
      "summary": "**完成時間**: 2025-10-31 **狀態**: ✅ 持續擴展進行中",
      "bullets": [
        "✅ 3個核心問題場景",
        "✅ 診斷工具",
        "`ComplianceDiagnostics` - 合規診斷工具",
        "`DataLeakageDetector` - 資料洩漏檢測器"
      ],
      "sourcePath": "鏡界/持續擴展完成報告-第二輪.md",
      "sourceUrl": "https://github.com/iiooiioo888/Note/blob/main/%E9%8F%A1%E7%95%8C/%E6%8C%81%E7%BA%8C%E6%93%B4%E5%B1%95%E5%AE%8C%E6%88%90%E5%A0%B1%E5%91%8A-%E7%AC%AC%E4%BA%8C%E8%BC%AA.md",
      "tags": [
        "doc"
      ]
    },
    {
      "title": "📖 鏡界平台 - 擴展內容使用指南",
      "summary": "**快速導航手冊 | 讓您充分利用平台的所有擴展功能**",
      "bullets": [
        "故障排查指南",
        "實戰範例集",
        "效能調優清單",
        "診斷工具"
      ],
      "sourcePath": "鏡界/擴展內容使用指南.md",
      "sourceUrl": "https://github.com/iiooiioo888/Note/blob/main/%E9%8F%A1%E7%95%8C/%E6%93%B4%E5%B1%95%E5%85%A7%E5%AE%B9%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97.md",
      "tags": [
        "doc"
      ]
    },
    {
      "title": "📝 文檔合併完成報告",
      "summary": "**合併時間**：2025-11-03 **版本**：v2.0.0",
      "bullets": [
        "✅ 保留 README.md 作為主文檔",
        "✅ 整合 index.md 的簡潔模組介紹",
        "✅ 合併相同的內容，避免重複",
        "✅ 保留兩者的優勢內容"
      ],
      "sourcePath": "鏡界/文檔合併完成報告.md",
      "sourceUrl": "https://github.com/iiooiioo888/Note/blob/main/%E9%8F%A1%E7%95%8C/%E6%96%87%E6%AA%94%E5%90%88%E4%BD%B5%E5%AE%8C%E6%88%90%E5%A0%B1%E5%91%8A.md",
      "tags": [
        "doc"
      ]
    },
    {
      "title": "🎉 鏡界平台 - 最終完成報告",
      "summary": "生成時間：2025-10-31 項目狀態：✅ **全面完成，達到企業級標準**",
      "bullets": [
        "✅ 刪除 Ch1 的 3 個重複文件",
        "✅ 重組 Ch9 的 7 個編號衝突文件",
        "✅ 更新所有相關鏈接",
        "✅ 創建項目 README.md"
      ],
      "sourcePath": "鏡界/最終完成報告.md",
      "sourceUrl": "https://github.com/iiooiioo888/Note/blob/main/%E9%8F%A1%E7%95%8C/%E6%9C%80%E7%B5%82%E5%AE%8C%E6%88%90%E5%A0%B1%E5%91%8A.md",
      "tags": [
        "doc"
      ]
    },
    {
      "title": "鏡界平台 - 架構優化完成報告",
      "summary": "基於IT結構分析報告的深入研究，鏡界平台成功實施了全面的架構簡化與優化。通過遵循KISS原則和YAGNI原則，我們在保持核心功能完整的前提下，顯著降低了系統複雜度、部署難度和資源需求。",
      "bullets": [
        "[x] 統一數據庫：6種 → 1種（PostgreSQL + TimescaleDB）",
        "移除MongoDB → PostgreSQL JSONB",
        "移除Elasticsearch → PostgreSQL全文搜索",
        "移除ClickHouse → PostgreSQL + TimescaleDB"
      ],
      "sourcePath": "鏡界/架構優化完成報告.md",
      "sourceUrl": "https://github.com/iiooiioo888/Note/blob/main/%E9%8F%A1%E7%95%8C/%E6%9E%B6%E6%A7%8B%E5%84%AA%E5%8C%96%E5%AE%8C%E6%88%90%E5%A0%B1%E5%91%8A.md",
      "tags": [
        "doc"
      ]
    },
    {
      "title": "鏡界平台 - 架構優化方案",
      "summary": "根據IT結構分析報告，鏡界平台存在以下關鍵問題：",
      "bullets": [
        "12個模組使用了Redis",
        "6個模組使用了PostgreSQL",
        "5個模組使用了Kubernetes",
        "4個模組使用了ELK Stack"
      ],
      "sourcePath": "鏡界/架構優化方案.md",
      "sourceUrl": "https://github.com/iiooiioo888/Note/blob/main/%E9%8F%A1%E7%95%8C/%E6%9E%B6%E6%A7%8B%E5%84%AA%E5%8C%96%E6%96%B9%E6%A1%88.md",
      "tags": [
        "doc"
      ]
    },
    {
      "title": "🎊 鏡界平台 - 架構完善完成報告（第三輪）",
      "summary": "**完成時間**: 2025-10-31 **狀態**: ✅ 架構完善完成",
      "bullets": [
        "無實時處理能力",
        "調度分散，資源利用率低",
        "數據質量管理薄弱",
        "缺少平台級支撐能力"
      ],
      "sourcePath": "鏡界/架構完善完成報告-第三輪.md",
      "sourceUrl": "https://github.com/iiooiioo888/Note/blob/main/%E9%8F%A1%E7%95%8C/%E6%9E%B6%E6%A7%8B%E5%AE%8C%E5%96%84%E5%AE%8C%E6%88%90%E5%A0%B1%E5%91%8A-%E7%AC%AC%E4%B8%89%E8%BC%AA.md",
      "tags": [
        "doc"
      ]
    },
    {
      "title": "🏗️ 鏡界平台 - 架構擴展與完善方案",
      "summary": "**設計日期**: 2025-10-31 **狀態**: 📋 設計中",
      "bullets": [
        "當前以批處理為主",
        "缺少流式數據處理",
        "無實時計算引擎",
        "各模塊獨立調度"
      ],
      "sourcePath": "鏡界/架構擴展與完善方案.md",
      "sourceUrl": "https://github.com/iiooiioo888/Note/blob/main/%E9%8F%A1%E7%95%8C/%E6%9E%B6%E6%A7%8B%E6%93%B4%E5%B1%95%E8%88%87%E5%AE%8C%E5%96%84%E6%96%B9%E6%A1%88.md",
      "tags": [
        "doc"
      ]
    },
    {
      "title": "📑 鏡界平台 - 模組功能與中間件快速參考",
      "summary": "| 模組 | 核心功能 | 主要中間件 | 數據流 | |------|---------|-----------|--------| | **Ch1 資料源註冊** | 元資料管理、版本控制、權限管理 | PostgreSQL, Elasticsearch, Redis | 輸入→註冊→存儲 | | **Ch2 指紋分析** | 技術棧識別、反爬檢測 | MongoDB, Scrapy, Redis | 網站→分析→指紋庫 | | **Ch3 健康監測** | 可用性檢查、異常告警 | InfluxDB, Prometheus, Alertmanager | 監測→指標→告警 |",
      "bullets": [
        "PostgreSQL, Redis, Nginx",
        "Docker, Kubernetes",
        "Prometheus, Grafana",
        "Elasticsearch, Kafka"
      ],
      "sourcePath": "鏡界/模組功能與中間件快速參考.md",
      "sourceUrl": "https://github.com/iiooiioo888/Note/blob/main/%E9%8F%A1%E7%95%8C/%E6%A8%A1%E7%B5%84%E5%8A%9F%E8%83%BD%E8%88%87%E4%B8%AD%E9%96%93%E4%BB%B6%E5%BF%AB%E9%80%9F%E5%8F%83%E8%80%83.md",
      "tags": [
        "doc"
      ]
    },
    {
      "title": "📦 鏡界平台 - 簡化版部署指南",
      "summary": "基於IT結構分析報告，簡化版部署指南遵循以下原則： - ✅ **最小化依賴**：從6種數據庫簡化到1種（PostgreSQL） - ✅ **快速啟動**：開發環境5分鐘內完成部署 - ✅ **漸進式複雜**：按需增加組件，而非一次性全部部署 - ✅ **清晰分層**：開發、測試、生產環境明確區分",
      "bullets": [
        "✅ 最小化依賴：從6種數據庫簡化到1種（PostgreSQL）",
        "✅ 快速啟動：開發環境5分鐘內完成部署",
        "✅ 漸進式複雜：按需增加組件，而非一次性全部部署",
        "✅ 清晰分層：開發、測試、生產環境明確區分"
      ],
      "sourcePath": "鏡界/部署指南-簡化版.md",
      "sourceUrl": "https://github.com/iiooiioo888/Note/blob/main/%E9%8F%A1%E7%95%8C/%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97-%E7%B0%A1%E5%8C%96%E7%89%88.md",
      "tags": [
        "doc"
      ]
    },
    {
      "title": "📋 需求列表說明文檔",
      "summary": "**創建日期**：2025-11-03 **位置**：README.md → \"📋 需求列表\" 章節",
      "bullets": [
        "🔴 高優先級（8項）：核心功能，急需完成",
        "🟡 中優先級（13項）：重要功能，計劃完成",
        "🟢 低優先級（19項）：增強功能，長期規劃",
        "✅ 需求項目名稱"
      ],
      "sourcePath": "鏡界/需求列表說明.md",
      "sourceUrl": "https://github.com/iiooiioo888/Note/blob/main/%E9%8F%A1%E7%95%8C/%E9%9C%80%E6%B1%82%E5%88%97%E8%A1%A8%E8%AA%AA%E6%98%8E.md",
      "tags": [
        "doc"
      ]
    },
    {
      "title": "🏆 鏡界平台 - 項目完成總報告",
      "summary": "**完成日期**: 2025-10-31 **項目狀態**: ✅ **全部完工！100% 完成**",
      "bullets": [
        "✅ Ch1 繁簡混用（3個重複文件）",
        "✅ Ch9 編號衝突（7個文件衝突）",
        "✅ 缺少項目總索引",
        "✅ 命名規範不統一（~74個文件）"
      ],
      "sourcePath": "鏡界/項目完成總報告-全部完工.md",
      "sourceUrl": "https://github.com/iiooiioo888/Note/blob/main/%E9%8F%A1%E7%95%8C/%E9%A0%85%E7%9B%AE%E5%AE%8C%E6%88%90%E7%B8%BD%E5%A0%B1%E5%91%8A-%E5%85%A8%E9%83%A8%E5%AE%8C%E5%B7%A5.md",
      "tags": [
        "doc"
      ]
    },
    {
      "title": "📋 鏡界平台 - 項目結構檢查報告",
      "summary": "**檢查時間**: 2025-10-31 **檢查範圍**: 完整項目結構 **狀態**: ✅ 結構完整，符合預期",
      "bullets": [
        "1-10: 模組概述、詳細功能清單、技術架構、核心組件、資料模型、API規範、效能優化、安全考慮、模組交互、最佳實踐",
        "X.11: 故障排查指南（8個章節有）",
        "X.12: 實戰範例集（Ch1, Ch2, Ch3 有）",
        "Ch9 特殊: 9.11-9.17 部署專屬章節"
      ],
      "sourcePath": "鏡界/項目結構檢查報告.md",
      "sourceUrl": "https://github.com/iiooiioo888/Note/blob/main/%E9%8F%A1%E7%95%8C/%E9%A0%85%E7%9B%AE%E7%B5%90%E6%A7%8B%E6%AA%A2%E6%9F%A5%E5%A0%B1%E5%91%8A.md",
      "tags": [
        "doc"
      ]
    }
  ],
}
