// Auto-generated by scripts/sync-three-realms.mjs — DO NOT EDIT
// Generated: 2026-05-13T07:39:41.438Z

export interface RealmFeatureCard {
  realmId: RealmId
  slug: string
  title: string
  summary: string
  bullets: string[]
  bodyMarkdown: string
  sourcePath: string
  sourceUrl: string
  tags: string[]
}

export type RealmId = 'tianyu' | 'shenyu' | 'jingjie'

export const REALMS_FEATURE_COUNTS: Record<RealmId, number> = {
  tianyu: 205,
  shenyu: 30,
  jingjie: 207,
}
