// Auto-generated by scripts/sync-three-realms.mjs — DO NOT EDIT
// Generated: 2026-05-13T08:07:12.644Z

export type TianyuCardKind =
  | 'conclusion'
  | 'interaction'
  | 'task'
  | 'knowledge'
  | 'doc'

export type TianyuPriorityRank = 'high' | 'medium' | 'low'

export type TianyuStatusRank = 'pending' | 'done' | 'mixed' | 'unknown'

export type TianyuTopicClusterId =
  | 'furniture_diy'
  | 'supply_chain'
  | 'mrp_system'
  | 'kpi_metrics'
  | 'risk_compliance'
  | 'data_quality'
  | 'general'

export interface RealmInteractionIteration {
  ordinal: number
  sourceSlug: string
  sourcePath: string
  sourceUrl: string
  createdAt?: string
  statusHint?: string
}

export interface RealmFeatureCard {
  realmId: RealmId
  slug: string
  title: string
  summary: string
  bullets: string[]
  bodyMarkdown: string
  sourcePath: string
  sourceUrl: string
  tags: string[]
  tianyuKind?: TianyuCardKind
  topicCluster?: TianyuTopicClusterId
  requestCanonicalId?: string
  interactionIterations?: RealmInteractionIteration[]
  iterationCount?: number
  priorityRank?: TianyuPriorityRank
  statusRank?: TianyuStatusRank
  maxNumericPriority?: number
}

export type RealmId = 'tianyu' | 'shenyu' | 'jingjie'

export const REALMS_FEATURE_COUNTS: Record<RealmId, number> = {
  tianyu: 169,
  shenyu: 30,
  jingjie: 207,
}
